version: '3.8'

services:
  malbouche-backend:
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ESP32_WEBSOCKET_PORT=8080
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - mosquitto
    networks:
      - malbouche-network

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - malbouche-network

networks:
  malbouche-network:
    driver: bridge

volumes:
  mosquitto-data:
  mosquitto-logs: